### ISSUE TITLE
Contact us form not working

### ISSUE THREAD

**Issue by Ahlyab** [Tayl-Amber/Portfolio#1]
# Issue
I tried using contact us form in your portfolio website and it's not working

# Suggestion
you can use JavaScript based library to handle contact us form

**Comment by eimaan-muzammil** [comment]
fix this issue as soon as possible

**Comment by Tayl-Amber** [comment]
Thanks for concerning.
I'll fix that as soon as possible.

**Comment by Tayl-Amber** [comment]
I took a look at that issue and it has been resolved. 
Now feel free to contact me through my portfolio website 😊
